name: CI/CD Pipeline for React App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 5: Build the React application
      - name: Build Application
        run: npm run build

      # Step 6: Set up Docker for containerization
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 7: Log in to Docker Registry (GitHub Container Registry in this case)
      - name: Log In to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      # Step 9: Checkout GitOps Repository
      - name: Checkout GitOps Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'master'
          repository: joshuakudo/fleet-infra
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gitops-repo

      # Step 10: Copy the build artifacts to the GitOps repo
      - name: Update GitOps Repository
        run: |
          # Create the 'deploy' directory if it doesn't exist
          mkdir -p gitops-repo/deploy
    
          # Copy the build artifacts to the GitOps repository
          cp -r build/* gitops-repo/deploy/
    
          # Navigate to the GitOps repository
          cd gitops-repo

          # Configure Git user for commit
          git config --global user.email "monleonjoshua00@gmail.com"
          git config --global user.name "joshuakudo"

          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/joshuakudo/fleet-infra.git
    
          # Commit and push the changes
          git add .
          git commit -m "Deploy new frontend build"
          git push
    
      # Step 11: Send Email Notification
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Actions: React App CI/CD Pipeline Status"
          body: |
            The CI/CD pipeline for your React app has been successfully completed.
            Details:
            - Repository: ${{ github.repository }}
            - Branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
          to: ${{ secrets.RECIPIENT_EMAILS }}
          from: ${{ secrets.SMTP_USERNAME }}
